language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - pyrus channel-discover pear.phpunit.de
  - pyrus channel-discover pear.symfony.com
  - pyrus install --force phpunit/DbUnit
  - phpenv rehash
  - mysql -e 'create database joomla_ut;'
  - mysql joomla_ut < tests/unit/suites/database/stubs/mysql.sql
  - psql -c 'create database joomla_ut;' -U postgres
  - psql -d joomla_ut -a -f tests/unit/suites/database/stubs/postgresql.sql

script:
  - phpunit --configuration travisci-phpunit.xml

branches:
  except:
    - 2.5.x

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18687d008d633d02aa84
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

